<a href="https://colab.research.google.com/github/PosgradoMNA/ActividadesAprendizaje-A01794419-IgnacioQuintero/blob/main/Module%205%20-%20Python_DataScience_IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science - IBM Course

### Ignacio Antonio Quintero Chávez - A01794419 / Module 5

### Numpy 1D Arrays

In [2]:
import numpy as np

In [ ]:
x = np.array([0, 1, 2, 3, 4])

In [ ]:
# Checking the type
type(x)

numpy.ndarray

In [ ]:
# Checking the number of elements in the array
print(x.size)

5


In [ ]:
# Checking the type of values stored in the array
x.dtype

dtype('int64')

In [ ]:
# Accesing each element via a square bracket
print("x[0]:", x[0])
print("x[1]:", x[1])
print("x[2]:", x[2])
print("x[3]:", x[3])
print("x[4]:", x[4])

x[0]: 0
x[1]: 1
x[2]: 2
x[3]: 3
x[4]: 4


### Indexing and Slicing

In [ ]:
my_array = ([1, 2, 3, 4, 5, 6, 7])
my_array

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
# Assign a new value
my_array[0] = 10
my_array

[10, 2, 3, 4, 5, 6, 7]

In [ ]:
my_array[0]

10

In [ ]:
# Selecting elements from the array
my_array[0:5]

[10, 2, 3, 4, 5]

In [ ]:
# Assigning the selected elements to a new numpy array
new_array = my_array[0:5]
new_array

[10, 2, 3, 4, 5]

In [ ]:
# We can also define the steps in slicing : [start:end:step]
print(my_array[0:7:2])

[10, 3, 5, 7]


In [ ]:
# Printing the array in reverse order is also possible
print(my_array[::-1])

[7, 6, 5, 4, 3, 2, 10]


In [ ]:
# Printing the even numbers
array_example = ([1, 2, 3, 4, 5, 6, 7, 8])
print(array_example[1::2])

[2, 4, 6, 8]


### Numpy Statistical Functions

In [ ]:
x = np.array([1, -1, 1, -1])

In [ ]:
# Obtain the mean of the array
mean = x.mean()
mean

0.0

In [ ]:
# Obtain the standard deviation of the array
std_deviation = x.std()
std_deviation

1.0

In [ ]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
# Obtain the biggest value in the array
max_value = y.max()
max_value

10

In [ ]:
# Obtain the smallest value in the array
min_value = y.min()
min_value

1

In [ ]:
# Get the sum of maximum and minimun value of the array 'z'
z = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Max value
value_max = z.max()

# Min value
value_min = z.min()

# Sum
total_sum = value_max + value_min
print(total_sum)

110


### Numpy Array Operations

In [ ]:
myFirstArray = np.array([1, 2])
myFirstArray

array([1, 2])

In [ ]:
mySecondArray = np.array([1, 2])
mySecondArray

array([1, 2])

In [ ]:
# Addition
result = np.add(myFirstArray, mySecondArray)
result

array([2, 4])

In [ ]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [ ]:
y = np.array([5, 10, 15])
y

array([ 5, 10, 15])

In [ ]:
# Subtraction
z = np.subtract(x, y)
z

array([ 5, 10, 15])

In [ ]:
a = np.array([10, 10])
a

array([10, 10])

In [ ]:
b = np.array([50, 40])
b

array([50, 40])

In [ ]:
# Multiplication
c = np.multiply(a, b)
c

array([500, 400])

In [ ]:
first_array = np.array([10, 20, 30])
first_array

array([10, 20, 30])

In [ ]:
second_array = np.array([2, 2, 2])
second_array

array([2, 2, 2])

In [ ]:
# Division
result = (np.divide(first_array, second_array))
result

array([ 5., 10., 15.])

In [ ]:
X = np.array([1, 2])
Y = np.array([5, 6])

In [ ]:
# Dot Product
np.dot(X, Y)

17

In [ ]:
example_1 = np.array([1,2,3,4])

In [ ]:
# Adding a constant
result = example_1 + 2
result

array([3, 4, 5, 6])

### Mathematical Functions

In [ ]:
# Accesing the value of pi using Numpy
np.pi

3.141592653589793

In [ ]:
# Create the numpy array in radians
x = np.array([1, np.pi/2, np.pi])
x

array([1.        , 1.57079633, 3.14159265])

In [ ]:
# Applying the function 'sin'
z = np.sin(x)
z

array([8.41470985e-01, 1.00000000e+00, 1.22464680e-16])

### Iterating

In [ ]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [ ]:
for x in my_array:
  print(x)

1
2
3


### Numpy 2D Arrays

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Creating a list
x = [[1, 2, 3], [20, 30, 40], [100, 200, 300]]
x

[[1, 2, 3], [20, 30, 40], [100, 200, 300]]

In [7]:
# Cast the list to a Numpy Array

my_array = np.array(x)
my_array

array([[  1,   2,   3],
       [ 20,  30,  40],
       [100, 200, 300]])

In [8]:
# Showing the numpy array dimensions
my_array.ndim

2

In [9]:
# Showing the numpy array shape
my_array.shape

(3, 3)

In [10]:
# Showing the numpy array size
my_array.size

9

### Accessing different elements of a Numpy Array

In [14]:
my_array

array([[  1,   2,   3],
       [ 20,  30,  40],
       [100, 200, 300]])

In [12]:
# Accessing the elements on the second row and third column
my_array[1, 2]

40

In [15]:
# Accesing the same element above using different notation
my_array[1][2]

40

In [16]:
# Accesing the element on the first row and first column
my_array[0, 0]

1

In [17]:
# Slicing - Accessing the element on the first row and first and second columns
my_array[0][0:2]

array([1, 2])

In [18]:
# Slicing - Accessing the element on the first and second rows and third colum
my_array[:2, 2]

array([ 3, 40])

### Basic Operations

In [19]:
# Creating a Numpy Array xy
xy = np.array([[1, 0], [0, 1]])
xy

array([[1, 0],
       [0, 1]])

In [20]:
# Creating a Numpy Array xz
xz = np.array([[10, 20], [30, 40]])
xz

array([[10, 20],
       [30, 40]])

In [21]:
# Add xy and xz
yz = xy + xz
yz

array([[11, 20],
       [30, 41]])

In [22]:
# Multiply xy with 2
result = 2 * xy
result

array([[2, 0],
       [0, 2]])

In [24]:
# Multiply xy and xz
total = xy * xz
total

array([[10,  0],
       [ 0, 40]])

In [27]:
# Creating matrix X
X = np.array([[0, 2, 4], [10, 20, 30]])
X

array([[ 0,  2,  4],
       [10, 20, 30]])

In [31]:
# Creating matrix Y
Y = np.array([[10, 50], [30, 40], [2, 4]])
Y

array([[10, 50],
       [30, 40],
       [ 2,  4]])

In [32]:
# Calculating the dot product
Z = np.dot(X, Y)
Z

array([[  68,   96],
       [ 760, 1420]])

In [33]:
# Calculating the sine of Z
np.sin(Z)

array([[-8.97927681e-01,  9.83587745e-01],
       [-2.62316677e-01,  1.20577413e-04]])