<a href="https://colab.research.google.com/github/PosgradoMNA/ActividadesAprendizaje-A01794419-IgnacioQuintero/blob/main/Module%205%20-%20Python_DataScience_IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science - IBM Course

### Ignacio Antonio Quintero Chávez - A01794419 / Module 5

### Numpy 1D Arrays

In [1]:
import numpy as np

In [2]:
x = np.array([0, 1, 2, 3, 4])

In [3]:
# Checking the type
type(x)

numpy.ndarray

In [7]:
# Checking the number of elements in the array
print(x.size)

5


In [18]:
# Checking the type of values stored in the array
x.dtype

dtype('int64')

In [14]:
# Accesing each element via a square bracket
print("x[0]:", x[0])
print("x[1]:", x[1])
print("x[2]:", x[2])
print("x[3]:", x[3])
print("x[4]:", x[4])

x[0]: 0
x[1]: 1
x[2]: 2
x[3]: 3
x[4]: 4


### Indexing and Slicing

In [15]:
my_array = ([1, 2, 3, 4, 5, 6, 7])
my_array

[1, 2, 3, 4, 5, 6, 7]

In [16]:
# Assign a new value
my_array[0] = 10
my_array

[10, 2, 3, 4, 5, 6, 7]

In [17]:
my_array[0]

10

In [20]:
# Selecting elements from the array
my_array[0:5]

[10, 2, 3, 4, 5]

In [21]:
# Assigning the selected elements to a new numpy array
new_array = my_array[0:5]
new_array

[10, 2, 3, 4, 5]

In [23]:
# We can also define the steps in slicing : [start:end:step]
print(my_array[0:7:2])

[10, 3, 5, 7]


In [25]:
# Printing the array in reverse order is also possible
print(my_array[::-1])

[7, 6, 5, 4, 3, 2, 10]


In [27]:
# Printing the even numbers
array_example = ([1, 2, 3, 4, 5, 6, 7, 8])
print(array_example[1::2])

[2, 4, 6, 8]


### Numpy Statistical Functions

In [28]:
x = np.array([1, -1, 1, -1])

In [29]:
# Obtain the mean of the array
mean = x.mean()
mean

0.0

In [30]:
# Obtain the standard deviation of the array
std_deviation = x.std()
std_deviation

1.0

In [31]:
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [34]:
# Obtain the biggest value in the array
max_value = y.max()
max_value

10

In [35]:
# Obtain the smallest value in the array
min_value = y.min()
min_value

1

In [36]:
# Get the sum of maximum and minimun value of the array 'z'
z = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Max value
value_max = z.max()

# Min value
value_min = z.min()

# Sum
total_sum = value_max + value_min
print(total_sum)

110


### Numpy Array Operations

In [42]:
myFirstArray = np.array([1, 2])
myFirstArray

array([1, 2])

In [43]:
mySecondArray = np.array([1, 2])
mySecondArray

array([1, 2])

In [44]:
# Addition
result = np.add(myFirstArray, mySecondArray)
result

array([2, 4])

In [45]:
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [46]:
y = np.array([5, 10, 15])
y

array([ 5, 10, 15])

In [48]:
# Subtraction
z = np.subtract(x, y)
z

array([ 5, 10, 15])

In [49]:
a = np.array([10, 10])
a

array([10, 10])

In [50]:
b = np.array([50, 40])
b

array([50, 40])

In [51]:
# Multiplication
c = np.multiply(a, b)
c

array([500, 400])

In [53]:
first_array = np.array([10, 20, 30])
first_array

array([10, 20, 30])

In [55]:
second_array = np.array([2, 2, 2])
second_array

array([2, 2, 2])

In [58]:
# Division
result = (np.divide(first_array, second_array))
result

array([ 5., 10., 15.])

In [59]:
X = np.array([1, 2])
Y = np.array([5, 6])

In [60]:
# Dot Product
np.dot(X, Y)

17

In [61]:
example_1 = np.array([1,2,3,4])

In [62]:
# Adding a constant
result = example_1 + 2
result

array([3, 4, 5, 6])

### Mathematical Functions

In [63]:
# Accesing the value of pi using Numpy
np.pi

3.141592653589793

In [65]:
# Create the numpy array in radians
x = np.array([1, np.pi/2, np.pi])
x

array([1.        , 1.57079633, 3.14159265])

In [66]:
# Applying the function 'sin'
z = np.sin(x)
z

array([8.41470985e-01, 1.00000000e+00, 1.22464680e-16])

### Iterating

In [68]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [69]:
for x in my_array:
  print(x)

1
2
3
